// Code generated by counterfeiter. DO NOT EDIT.
package clifakes

import (
	"context"
	"sync"

	"github.com/jhoblitt/gnome-monitor-pin/internal/cli"
	"github.com/jhoblitt/gnome-monitor-pin/internal/layout"
)

type FakeDisplay struct {
	ApplyStub        func(context.Context, layout.Target) error
	applyMutex       sync.RWMutex
	applyArgsForCall []struct {
		arg1 context.Context
		arg2 layout.Target
	}
	applyReturns struct {
		result1 error
	}
	applyReturnsOnCall map[int]struct {
		result1 error
	}
	CloseStub        func() error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
	}
	closeReturns struct {
		result1 error
	}
	closeReturnsOnCall map[int]struct {
		result1 error
	}
	CurrentStateStub        func(context.Context) (layout.State, error)
	currentStateMutex       sync.RWMutex
	currentStateArgsForCall []struct {
		arg1 context.Context
	}
	currentStateReturns struct {
		result1 layout.State
		result2 error
	}
	currentStateReturnsOnCall map[int]struct {
		result1 layout.State
		result2 error
	}
	SubscribeStub        func(context.Context) (<-chan struct{}, error)
	subscribeMutex       sync.RWMutex
	subscribeArgsForCall []struct {
		arg1 context.Context
	}
	subscribeReturns struct {
		result1 <-chan struct{}
		result2 error
	}
	subscribeReturnsOnCall map[int]struct {
		result1 <-chan struct{}
		result2 error
	}
	VerifyStub        func(context.Context, layout.Target) error
	verifyMutex       sync.RWMutex
	verifyArgsForCall []struct {
		arg1 context.Context
		arg2 layout.Target
	}
	verifyReturns struct {
		result1 error
	}
	verifyReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDisplay) Apply(arg1 context.Context, arg2 layout.Target) error {
	fake.applyMutex.Lock()
	ret, specificReturn := fake.applyReturnsOnCall[len(fake.applyArgsForCall)]
	fake.applyArgsForCall = append(fake.applyArgsForCall, struct {
		arg1 context.Context
		arg2 layout.Target
	}{arg1, arg2})
	stub := fake.ApplyStub
	fakeReturns := fake.applyReturns
	fake.recordInvocation("Apply", []interface{}{arg1, arg2})
	fake.applyMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDisplay) ApplyCallCount() int {
	fake.applyMutex.RLock()
	defer fake.applyMutex.RUnlock()
	return len(fake.applyArgsForCall)
}

func (fake *FakeDisplay) ApplyCalls(stub func(context.Context, layout.Target) error) {
	fake.applyMutex.Lock()
	defer fake.applyMutex.Unlock()
	fake.ApplyStub = stub
}

func (fake *FakeDisplay) ApplyArgsForCall(i int) (context.Context, layout.Target) {
	fake.applyMutex.RLock()
	defer fake.applyMutex.RUnlock()
	argsForCall := fake.applyArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeDisplay) ApplyReturns(result1 error) {
	fake.applyMutex.Lock()
	defer fake.applyMutex.Unlock()
	fake.ApplyStub = nil
	fake.applyReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeDisplay) ApplyReturnsOnCall(i int, result1 error) {
	fake.applyMutex.Lock()
	defer fake.applyMutex.Unlock()
	fake.ApplyStub = nil
	if fake.applyReturnsOnCall == nil {
		fake.applyReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.applyReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeDisplay) Close() error {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
	}{})
	stub := fake.CloseStub
	fakeReturns := fake.closeReturns
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDisplay) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *FakeDisplay) CloseCalls(stub func() error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *FakeDisplay) CloseReturns(result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeDisplay) CloseReturnsOnCall(i int, result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeDisplay) CurrentState(arg1 context.Context) (layout.State, error) {
	fake.currentStateMutex.Lock()
	ret, specificReturn := fake.currentStateReturnsOnCall[len(fake.currentStateArgsForCall)]
	fake.currentStateArgsForCall = append(fake.currentStateArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.CurrentStateStub
	fakeReturns := fake.currentStateReturns
	fake.recordInvocation("CurrentState", []interface{}{arg1})
	fake.currentStateMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDisplay) CurrentStateCallCount() int {
	fake.currentStateMutex.RLock()
	defer fake.currentStateMutex.RUnlock()
	return len(fake.currentStateArgsForCall)
}

func (fake *FakeDisplay) CurrentStateCalls(stub func(context.Context) (layout.State, error)) {
	fake.currentStateMutex.Lock()
	defer fake.currentStateMutex.Unlock()
	fake.CurrentStateStub = stub
}

func (fake *FakeDisplay) CurrentStateArgsForCall(i int) context.Context {
	fake.currentStateMutex.RLock()
	defer fake.currentStateMutex.RUnlock()
	argsForCall := fake.currentStateArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeDisplay) CurrentStateReturns(result1 layout.State, result2 error) {
	fake.currentStateMutex.Lock()
	defer fake.currentStateMutex.Unlock()
	fake.CurrentStateStub = nil
	fake.currentStateReturns = struct {
		result1 layout.State
		result2 error
	}{result1, result2}
}

func (fake *FakeDisplay) CurrentStateReturnsOnCall(i int, result1 layout.State, result2 error) {
	fake.currentStateMutex.Lock()
	defer fake.currentStateMutex.Unlock()
	fake.CurrentStateStub = nil
	if fake.currentStateReturnsOnCall == nil {
		fake.currentStateReturnsOnCall = make(map[int]struct {
			result1 layout.State
			result2 error
		})
	}
	fake.currentStateReturnsOnCall[i] = struct {
		result1 layout.State
		result2 error
	}{result1, result2}
}

func (fake *FakeDisplay) Subscribe(arg1 context.Context) (<-chan struct{}, error) {
	fake.subscribeMutex.Lock()
	ret, specificReturn := fake.subscribeReturnsOnCall[len(fake.subscribeArgsForCall)]
	fake.subscribeArgsForCall = append(fake.subscribeArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.SubscribeStub
	fakeReturns := fake.subscribeReturns
	fake.recordInvocation("Subscribe", []interface{}{arg1})
	fake.subscribeMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDisplay) SubscribeCallCount() int {
	fake.subscribeMutex.RLock()
	defer fake.subscribeMutex.RUnlock()
	return len(fake.subscribeArgsForCall)
}

func (fake *FakeDisplay) SubscribeCalls(stub func(context.Context) (<-chan struct{}, error)) {
	fake.subscribeMutex.Lock()
	defer fake.subscribeMutex.Unlock()
	fake.SubscribeStub = stub
}

func (fake *FakeDisplay) SubscribeArgsForCall(i int) context.Context {
	fake.subscribeMutex.RLock()
	defer fake.subscribeMutex.RUnlock()
	argsForCall := fake.subscribeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeDisplay) SubscribeReturns(result1 <-chan struct{}, result2 error) {
	fake.subscribeMutex.Lock()
	defer fake.subscribeMutex.Unlock()
	fake.SubscribeStub = nil
	fake.subscribeReturns = struct {
		result1 <-chan struct{}
		result2 error
	}{result1, result2}
}

func (fake *FakeDisplay) SubscribeReturnsOnCall(i int, result1 <-chan struct{}, result2 error) {
	fake.subscribeMutex.Lock()
	defer fake.subscribeMutex.Unlock()
	fake.SubscribeStub = nil
	if fake.subscribeReturnsOnCall == nil {
		fake.subscribeReturnsOnCall = make(map[int]struct {
			result1 <-chan struct{}
			result2 error
		})
	}
	fake.subscribeReturnsOnCall[i] = struct {
		result1 <-chan struct{}
		result2 error
	}{result1, result2}
}

func (fake *FakeDisplay) Verify(arg1 context.Context, arg2 layout.Target) error {
	fake.verifyMutex.Lock()
	ret, specificReturn := fake.verifyReturnsOnCall[len(fake.verifyArgsForCall)]
	fake.verifyArgsForCall = append(fake.verifyArgsForCall, struct {
		arg1 context.Context
		arg2 layout.Target
	}{arg1, arg2})
	stub := fake.VerifyStub
	fakeReturns := fake.verifyReturns
	fake.recordInvocation("Verify", []interface{}{arg1, arg2})
	fake.verifyMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDisplay) VerifyCallCount() int {
	fake.verifyMutex.RLock()
	defer fake.verifyMutex.RUnlock()
	return len(fake.verifyArgsForCall)
}

func (fake *FakeDisplay) VerifyCalls(stub func(context.Context, layout.Target) error) {
	fake.verifyMutex.Lock()
	defer fake.verifyMutex.Unlock()
	fake.VerifyStub = stub
}

func (fake *FakeDisplay) VerifyArgsForCall(i int) (context.Context, layout.Target) {
	fake.verifyMutex.RLock()
	defer fake.verifyMutex.RUnlock()
	argsForCall := fake.verifyArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeDisplay) VerifyReturns(result1 error) {
	fake.verifyMutex.Lock()
	defer fake.verifyMutex.Unlock()
	fake.VerifyStub = nil
	fake.verifyReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeDisplay) VerifyReturnsOnCall(i int, result1 error) {
	fake.verifyMutex.Lock()
	defer fake.verifyMutex.Unlock()
	fake.VerifyStub = nil
	if fake.verifyReturnsOnCall == nil {
		fake.verifyReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.verifyReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeDisplay) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDisplay) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cli.Display = new(FakeDisplay)
